"""#493 cookie-less SuperGrok generate-plan. No invented lifts. No public unauth."""

from __future__ import annotations

import json
import os
import unittest
from unittest import mock

from api.auth.session_util import SESSION_COOKIE, make_session
from api.workout._util import (
    agent_generate_plan_body,
    agent_today_body,
    dispatch_client_route,
)
from rt_dashboard.agent_plan import (
    ensure_today_grok_plan,
    house_plan_user_id,
    overlay_workout_on_payload,
)
from rt_dashboard.agent_today import export_agent_today
from rt_dashboard.workout_plan_store import clear_memory_workout_plans

PULL_PLAN = {
    "session_type": "pull",
    "is_rest_day": False,
    "exercises": [
        {
            "name": "DB Row",
            "prescription": {"sets": 2, "reps": 8, "weight_lbs": 50},
        }
    ],
    "message": "Generated by SuperGrok.",
    "source": "grok",
    "empty": False,
}

REST_STAMP = {
    "session_type": "rest",
    "is_rest_day": True,
    "exercises": [],
    "empty": False,
    "message": "Recovery score 35 is below threshold (40).",
    "next_session_type": "pull",
}


def _token_headers():
    return {"X-FitDash-Service-Token": "house-secret"}


class HouseUserId(unittest.TestCase):
    def test_prefers_real_user_over_default(self):
        env = {"FITDASH_USER_ID": "default", "FITDASH_INVENTORY_AGENT_USER_ID": "chris-sub"}
        with mock.patch.dict(os.environ, env, clear=True):
            self.assertEqual(house_plan_user_id(), "chris-sub")

    def test_fitdash_user_id_wins_when_set(self):
        env = {"FITDASH_USER_ID": "chris-sub"}
        with mock.patch.dict(os.environ, env, clear=True):
            self.assertEqual(house_plan_user_id(), "chris-sub")


class EnsureToday(unittest.TestCase):
    def setUp(self):
        clear_memory_workout_plans()

    def tearDown(self):
        clear_memory_workout_plans()

    def test_skips_rest_days_without_grok(self):
        with mock.patch(
            "rt_dashboard.agent_plan.generate_grok_plans"
        ) as gen:
            out = ensure_today_grok_plan(
                "sub-1",
                day="2026-09-06",
                context={
                    "day": "2026-09-06",
                    "catalog": {"exercises": []},
                    "sessions": [],
                    "goals": {"rotation": ["push", "pull", "legs"]},
                    "recovery": {},
                    "stamped": REST_STAMP,
                },
            )
        gen.assert_not_called()
        self.assertTrue(out["ok"])
        self.assertEqual(out["skipped"], "rest")
        self.assertFalse(out["generated"])

    def test_persists_supergrok_plan_once(self):
        grok = {
            "ok": True,
            "workout": PULL_PLAN,
            "meal": {"items": [], "empty": True},
            "model": "grok-test",
        }
        ctx = {
            "day": "2026-09-06",
            "catalog": {"exercises": [{"name": "DB Row"}]},
            "sessions": [],
            "goals": {"rotation": ["push", "pull", "legs"]},
            "recovery": {},
            "stamped": {
                "session_type": "pull",
                "is_rest_day": False,
                "exercises": [],
                "next_session_type": "pull",
            },
            "next_session_type": "pull",
        }
        with mock.patch(
            "rt_dashboard.agent_plan.generate_grok_plans", return_value=grok
        ) as gen:
            first = ensure_today_grok_plan("sub-1", day="2026-09-06", context=ctx)
            second = ensure_today_grok_plan("sub-1", day="2026-09-06", context=ctx)
        self.assertEqual(gen.call_count, 1)
        self.assertTrue(first["ok"])
        self.assertTrue(first["generated"])
        self.assertEqual(first["workout"]["exercises"][0]["name"], "DB Row")
        self.assertTrue(second["ok"])
        self.assertEqual(second["skipped"], "already_generated")
        self.assertFalse(second["generated"])

    def test_non_vercel_falls_back_to_local_supergrok_auth(self):
        ctx = {
            "day": "2026-09-06",
            "catalog": {"exercises": [{"name": "DB Row"}]},
            "sessions": [],
            "goals": {"rotation": ["push", "pull", "legs"]},
            "recovery": {},
            "stamped": {
                "session_type": "pull",
                "is_rest_day": False,
                "exercises": [],
            },
        }
        calls = []

        def fake_gen(user_id, **kwargs):
            calls.append(user_id)
            if user_id:
                return {
                    "ok": False,
                    "error": "Connect SuperGrok to generate today's meal/workout plan.",
                    "workout": {"session_type": "pull", "exercises": [], "empty": True},
                }
            return {"ok": True, "workout": PULL_PLAN, "meal": {"items": [], "empty": True}}

        with mock.patch.dict(os.environ, {}, clear=True), mock.patch(
            "rt_dashboard.agent_plan.generate_grok_plans", side_effect=fake_gen
        ):
            out = ensure_today_grok_plan("sub-1", day="2026-09-06", context=ctx)
        self.assertEqual(calls, ["sub-1", ""])
        self.assertTrue(out["ok"])
        self.assertEqual(out["workout"]["exercises"][0]["name"], "DB Row")

    def test_does_not_invent_when_grok_fails(self):
        ctx = {
            "day": "2026-09-06",
            "catalog": {"exercises": [{"name": "DB Row"}]},
            "sessions": [],
            "goals": {"rotation": ["push", "pull", "legs"]},
            "recovery": {},
            "stamped": {
                "session_type": "pull",
                "is_rest_day": False,
                "exercises": [],
            },
        }
        with mock.patch(
            "rt_dashboard.agent_plan.generate_grok_plans",
            return_value={
                "ok": False,
                "error": "Connect SuperGrok to generate today's meal/workout plan.",
                "workout": {"session_type": "pull", "exercises": [], "empty": True},
            },
        ):
            out = ensure_today_grok_plan("sub-1", day="2026-09-06", context=ctx)
        self.assertFalse(out["ok"])
        self.assertIn("Connect SuperGrok", out["error"])
        self.assertEqual((out["workout"] or {}).get("exercises") or [], [])

    def test_empty_grok_success_is_loud_fail(self):
        ctx = {
            "day": "2026-09-06",
            "catalog": {"exercises": [{"name": "DB Row"}]},
            "sessions": [],
            "goals": {"rotation": ["push", "pull", "legs"]},
            "recovery": {},
            "stamped": {
                "session_type": "pull",
                "is_rest_day": False,
                "exercises": [],
            },
        }
        with mock.patch(
            "rt_dashboard.agent_plan.generate_grok_plans",
            return_value={
                "ok": True,
                "workout": {
                    "session_type": "pull",
                    "is_rest_day": False,
                    "exercises": [],
                    "empty": True,
                },
            },
        ):
            out = ensure_today_grok_plan("sub-1", day="2026-09-06", context=ctx)
        self.assertFalse(out["ok"])
        self.assertTrue(out["error"])
        self.assertIn(
            out["error"],
            ("not a good workout_plan", "SuperGrok returned no exercises"),
        )


class AgentGenerateHttp(unittest.TestCase):
    def setUp(self):
        clear_memory_workout_plans()

    def tearDown(self):
        clear_memory_workout_plans()

    def test_cookie_less_without_token_is_401(self):
        with mock.patch.dict(os.environ, {}, clear=True):
            status, body = agent_generate_plan_body({}, {})
        self.assertEqual(status, 401)
        self.assertEqual(body["error"], "auth_required")
        self.assertNotIn("plan", body)
        self.assertNotIn("<html", json.dumps(body).lower())

    def test_dispatch_get_is_405(self):
        env = {"FITDASH_SERVICE_TOKEN": "house-secret", "FITDASH_SERVICE_LOOPBACK": "0"}
        with mock.patch.dict(os.environ, env, clear=True):
            status, body = dispatch_client_route(
                _token_headers(),
                "_r=agent_generate",
                "GET",
            )
        self.assertEqual(status, 405)
        self.assertEqual(body["error"], "method_not_allowed")

    def test_token_generate_persists_into_today(self):
        env = {
            "FITDASH_SERVICE_TOKEN": "house-secret",
            "FITDASH_SERVICE_LOOPBACK": "0",
            "FITDASH_USER_ID": "sub-1",
        }
        grok = {
            "ok": True,
            "workout": PULL_PLAN,
            "meal": {"items": [], "empty": True},
        }
        with mock.patch.dict(os.environ, env, clear=True):
            with mock.patch(
                "rt_dashboard.agent_plan.generate_grok_plans", return_value=grok
            ), mock.patch(
                "rt_dashboard.agent_plan._load_generate_kwargs",
                return_value={
                    "day": "2026-09-06",
                    "catalog": {"exercises": [{"name": "DB Row"}]},
                    "sessions": [],
                    "goals": {"rotation": ["push", "pull", "legs"]},
                    "recovery": {"sparse": True},
                    "stamped": {
                        "session_type": "pull",
                        "is_rest_day": False,
                        "exercises": [],
                        "next_session_type": "pull",
                    },
                    "next_session_type": "pull",
                    "sessions_brief": [],
                    "equipment": {"items": []},
                    "inventory": {"ingredients": []},
                    "targets": {},
                    "consumed": {},
                    "food_logs_today": [],
                },
            ):
                status, body = agent_generate_plan_body(_token_headers(), {})
        self.assertEqual(status, 200)
        self.assertTrue(body["ok"])
        self.assertTrue(body["generated"])
        self.assertEqual(body["plan"]["exercises"][0]["name"], "DB Row")
        self.assertNotIn("house-secret", json.dumps(body))

        overlay = overlay_workout_on_payload(
            {"coach": {"today": {"date": "2026-09-06"}}},
            body["plan"],
        )
        today = export_agent_today(overlay)
        self.assertEqual(today["today"]["workout"]["session_type"], "pull")
        self.assertEqual(today["today"]["workout"]["plan_exercises"][0]["name"], "DB Row")
        self.assertEqual(today["today"]["workout"]["plan_exercises"][0]["weight_lbs"], 50)
        self.assertFalse(today["today"]["workout"]["empty"])

    def test_signed_in_still_works(self):
        env = {"GOOGLE_CLIENT_SECRET": "test-secret"}
        with mock.patch.dict(os.environ, env, clear=True):
            token = make_session(
                {"id": "sub-1", "email": "c@example.com", "display_name": "Chris"}
            )
            headers = {"Cookie": f"{SESSION_COOKIE}={token}"}
            with mock.patch(
                "rt_dashboard.agent_plan.ensure_today_grok_plan",
                return_value={
                    "ok": True,
                    "skipped": "rest",
                    "generated": False,
                    "workout": REST_STAMP,
                    "persist": {"ok": False},
                    "error": None,
                },
            ):
                status, body = agent_generate_plan_body(headers, {})
        self.assertEqual(status, 200)
        self.assertTrue(body["ok"])
        self.assertEqual(body["skipped"], "rest")


class TodayAutoGenerate(unittest.TestCase):
    def setUp(self):
        clear_memory_workout_plans()

    def tearDown(self):
        clear_memory_workout_plans()

    def test_cookie_less_today_surfaces_generate_error(self):
        env = {
            "FITDASH_SERVICE_TOKEN": "house-secret",
            "FITDASH_SERVICE_LOOPBACK": "0",
            "FITDASH_USER_ID": "sub-1",
            "TZ": "UTC",
        }
        pull_slot = {
            "session_type": "pull",
            "is_rest_day": False,
            "exercises": [],
            "empty": True,
            "message": "SuperGrok connected. Generate today's meal/workout plan.",
            "next_session_type": "pull",
        }
        with mock.patch.dict(os.environ, env, clear=True):
            with mock.patch(
                "api.dashboard._load_sessions", return_value=([], [], "turso")
            ), mock.patch(
                "rt_dashboard.google_health.GoogleHealthClient.credentials_present",
                return_value=False,
            ), mock.patch(
                "rt_dashboard.hidrate_client.hidrate_bottle_charge",
                return_value={"available": False, "percent": None},
            ), mock.patch(
                "rt_dashboard.hidrate_client.hidrate_hydration_samples",
                return_value=[],
            ), mock.patch(
                "rt_dashboard.grok_planner.dashboard_plan_slots",
                return_value=({}, pull_slot),
            ), mock.patch(
                "rt_dashboard.agent_plan.ensure_today_grok_plan",
                return_value={
                    "ok": False,
                    "error": "SuperGrok replied but the plan was not valid JSON. Try generate again.",
                    "workout": {"session_type": "pull", "exercises": [], "empty": True},
                    "generated": False,
                },
            ):
                status, body = agent_today_body(_token_headers(), "")
        self.assertEqual(status, 200)
        wo = body["today"]["workout"]
        self.assertEqual(wo.get("plan_exercises") or [], [])
        self.assertIn("valid JSON", wo.get("generate_error") or wo.get("message") or "")
