"""Last-good SuperGrok workout persist: user+day key, no invented lifts."""

from __future__ import annotations

import unittest
from unittest import mock

from rt_dashboard.workout_plan_store import (
    clear_memory_workout_plans,
    flatten_plan_exercises,
    is_good_workout_plan,
    load_last_good_workout_plan,
    persist_key,
    save_last_good_workout_plan,
)

GOOD = {
    "session_type": "pull",
    "is_rest_day": False,
    "exercises": [
        {
            "name": "DB Row",
            "prescription": {"sets": 2, "reps": 8, "weight_lbs": 50},
        }
    ],
    "message": "Generated by SuperGrok.",
    "source": "grok",
}
EMPTY = {
    "session_type": "pull",
    "is_rest_day": False,
    "exercises": [],
    "message": "SuperGrok connected. Generate today's meal/workout plan.",
}
REST = {
    "session_type": "rest",
    "is_rest_day": True,
    "exercises": [],
    "message": "Recovery score 35 is below threshold (40).",
}


class FlattenAndGood(unittest.TestCase):
    def test_flatten_promotes_prescription(self):
        rows = flatten_plan_exercises(GOOD["exercises"])
        self.assertEqual(rows[0]["name"], "DB Row")
        self.assertEqual(rows[0]["sets"], 2)
        self.assertEqual(rows[0]["reps"], 8)
        self.assertEqual(rows[0]["weight_lbs"], 50)

    def test_empty_and_rest_are_not_good(self):
        self.assertTrue(is_good_workout_plan(GOOD))
        self.assertFalse(is_good_workout_plan(EMPTY))
        self.assertFalse(is_good_workout_plan(REST))
        self.assertFalse(is_good_workout_plan(None))
        self.assertFalse(is_good_workout_plan({"exercises": [{"sets": 2}]}))


class PersistMemory(unittest.TestCase):
    def setUp(self):
        clear_memory_workout_plans()

    def tearDown(self):
        clear_memory_workout_plans()

    def test_key_is_user_and_civil_day(self):
        key = persist_key("sub-1", "2026-09-06T15:04:05-04:00")
        self.assertEqual(key, {"user_id": "sub-1", "local_today": "2026-09-06"})

    def test_empty_does_not_persist(self):
        with mock.patch("rt_dashboard.turso_http.turso_enabled", return_value=False):
            out = save_last_good_workout_plan("sub-1", "2026-09-06", EMPTY)
        self.assertFalse(out["ok"])
        self.assertEqual(out["error"], "not a good workout_plan")
        self.assertIsNone(load_last_good_workout_plan("sub-1", "2026-09-06"))

    def test_good_plan_roundtrip_without_turso(self):
        with mock.patch("rt_dashboard.turso_http.turso_enabled", return_value=False):
            out = save_last_good_workout_plan("sub-1", "2026-09-06", GOOD)
            loaded = load_last_good_workout_plan("sub-1", "2026-09-06")
        self.assertTrue(out["ok"])
        self.assertEqual(out["store"], "memory")
        self.assertEqual(loaded["exercises"][0]["name"], "DB Row")
        self.assertEqual(loaded["exercises"][0]["weight_lbs"], 50)
        self.assertIsNone(load_last_good_workout_plan("sub-1", "2026-09-05"))
        self.assertIsNone(load_last_good_workout_plan("other", "2026-09-06"))
